Add uiautomator snippet.
google/mobly-bundled-snippets pull request #132
Opened 2020-09-14 06:48 UTC by syaoranx

Add a snippet to dump UI hierarchy XML.

- Use uiautomator 2.2 
- Change minSdkVersion from 15 to 18

2020-09-14 09:21 UTC, xpconanfan requested changes

2020-09-14 09:21 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +    public String dumpUi() {
Something like `uiautomatorDumpWindowHierarchy`?

2020-09-14 09:21 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            if (BuildConfig.DEBUG) {
why do we make this decision based on build type?

2020-09-14 10:26 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +    public String dumpUi() {
Great suggestion. Change name to uiautomatorDumpWindowHierarchy.

2020-09-14 10:27 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            if (BuildConfig.DEBUG) {
Because I got a lint error "Unconditional Logging Calls". And it is one of its suggestions.
Or could I ignore the lint message and remove the decision?

2020-09-16 14:25 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            if (BuildConfig.DEBUG) {
Can we just let the exception through?

2020-09-21 08:58 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            if (BuildConfig.DEBUG) {
How about return exception in string like this?

2020-10-06 10:34 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +
why this extra line?

2020-10-07 07:05 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +
It is unused extra line, I've removed it.

2020-10-07 10:16 UTC, xpconanfan requested changes

2020-10-07 10:16 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +
why this extra line?

2020-10-07 10:16 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            res = "Dump error.";
I thought we were gonna let this error throw in this case?

2020-10-08 07:09 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +
It doesn't have any function, remove it.

2020-10-08 07:10 UTC, syaoranx commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +            res = "Dump error.";
I've changed to throw the exception here.

2020-10-14 10:53 UTC, syaoranx reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/132)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @xpconanfan)

___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 36 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r1-36:-MJ62BIIDPTCj9XNxVjb:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a692e8909e905aaa26e5b32c4efa83ed5d76988a/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L36)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

Great suggestion. Change name to uiautomatorDumpWindowHierarchy.
</blockquote></details>

Done.
___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 44 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r1-44:-MJ62D7MADsvCJvZSouv:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a692e8909e905aaa26e5b32c4efa83ed5d76988a/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L44)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

How about return exception in string like this?
</blockquote></details>

Done.
___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 35 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r4-35:-MJ629AoDzmWi4DecatI:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/78951badf46cbbf78f40fe14f85c151f96c4dd9c/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L35)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

It is unused extra line, I've removed it.
</blockquote></details>

Done.
___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 40 at r5](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r5-40:-MJ62BiM9Evo2E2lKbga:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/60a7099056726d5f118fb56df4cc3bd918d9011a/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L40)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

It doesn't have any function, remove it.
</blockquote></details>

Done.
___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 42 at r5](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r5-42:-MJ62De23yrsCI8Ms2HV:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/60a7099056726d5f118fb56df4cc3bd918d9011a/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L42)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

I've changed to throw the exception here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-21 06:28 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/132)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @syaoranx and @xpconanfan)

___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 44 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MHAMpgvMxfqmO_jKPVc-r1-44:-MK8q61ICoZS9DzWvC90:btznxow) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a692e8909e905aaa26e5b32c4efa83ed5d76988a/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L44)):*
<details><summary><i>Previously, syaoranx (Syaoran Kuo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no need to catch and re-throw?


<!-- Sent from Reviewable.io -->

2020-10-21 06:29 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/132)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @syaoranx)

___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 29 at r6](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MK8qLk_6YWFUb-XOagV:-MK8qLk_6YWFUb-XOagW:b-l6mwxj) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8863b109576b298aeac3f668ef8160e96b6eada6/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L29)):*
> ```Java
> /** Snippet class exposing Android APIs in Uiautomator. */
> public class UiautomatorSnippet implements Snippet {
>     private static final String TAG = UiautomatorSnippet.class.getCanonicalName();
> ```

remove


<!-- Sent from Reviewable.io -->

2020-10-21 06:34 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/132)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @syaoranx)

___
*[src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java, line 42 at r6](https://reviewable.io/reviews/google/mobly-bundled-snippets/132#-MK8rM-D7ecXqE_T24bS:-MK8rM-D7ecXqE_T24bT:b-lzrsg4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8863b109576b298aeac3f668ef8160e96b6eada6/src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java#L42)):*
> ```Java
>         } catch (IOException e) {
>             throw e;
>         }
> ```

close the stream


<!-- Sent from Reviewable.io -->

2020-10-21 06:47 UTC, eric100lin commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +    public String uiautomatorDumpWindowHierarchy() throws IOException{
I think it's better to have one space after 'IOException'.
`throws IOException {`

2020-10-21 09:21 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
> +    public String uiautomatorDumpWindowHierarchy() throws IOException{
+1

2020-11-02 03:28 UTC, merged