Refactored bluetooth enable/disable method RPCs
google/mobly-bundled-snippets pull request #134
Opened 2020-10-27 19:04 UTC by tprotopopov-dev

This change should prevent bluetooth failures during turning On/Off.

2020-10-28 03:11 UTC, xpconanfan requested changes

2020-10-28 03:11 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    /** Waits until bluetooth adapter state becomes consistent. */
Add javadoc explaining the mechanism of this method.
Seems more complicated than a simple wait

2020-10-28 03:11 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
>          // TODO(jwang1013): change it to SDK version for R after R is released.
Can you fulfill this TODO now that R is released

2020-10-28 03:11 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> -    @Rpc(description = "Enable bluetooth with a 30s timeout.")
why remove the timeout info?

2020-10-28 03:11 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +        Set<Integer> btStates = new HashSet<>();
seems a bit too complicated to keep track of five ints. is it possible to simplify this logic?

2020-10-28 17:39 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> -    @Rpc(description = "Enable bluetooth with a 30s timeout.")
Timeout is irrelevant and can change.

2020-10-28 19:56 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    /** Waits until bluetooth adapter state becomes consistent. */
done

2020-10-28 19:57 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +        Set<Integer> btStates = new HashSet<>();
Updated.

2020-10-28 20:10 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
>          // TODO(jwang1013): change it to SDK version for R after R is released.
Done

2020-10-31 02:35 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> -    @Rpc(description = "Enable bluetooth with a 30s timeout.")
It is hard coded and the users cannot change it, so we should not remove this?

2020-10-31 02:39 UTC, xpconanfan requested changes

2020-10-31 02:39 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +     * Waits until the bluetooth adapter state becomes consistent. We consider BT state consistent
"becomes consistent" -> "has stabilized"?

2020-10-31 02:39 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +     * Waits until the bluetooth adapter state becomes consistent. We consider BT state consistent
"state consistent" -> "state stabilized"

2020-10-31 02:39 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +                        "Failed to reach stable Bluetooth state within %d ms",
"reach a stable"

2020-10-31 02:39 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +                        "Failed to reach stable Bluetooth state within %d ms",
the unit should be "second" to be consistent with the other error messages.

2020-11-02 16:16 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> -    @Rpc(description = "Enable bluetooth with a 30s timeout.")
Updated.

2020-11-02 16:16 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +     * Waits until the bluetooth adapter state becomes consistent. We consider BT state consistent
Done.

2020-11-02 16:16 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +                        "Failed to reach stable Bluetooth state within %d ms",
Done.

2020-11-02 16:16 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +                        "Failed to reach stable Bluetooth state within %d ms",
Done.

2020-11-02 16:16 UTC, tprotopopov-dev commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +     * Waits until the bluetooth adapter state becomes consistent. We consider BT state consistent
Done.

2020-11-04 00:50 UTC, xpconanfan approved these changes

2020-11-04 00:51 UTC, merged