Have wifiClearConfiguredNetworks re-check network list to determine operation success.
google/mobly-bundled-snippets pull request #146
Opened 2022-01-11 22:45 UTC by xianyuanjia

Sometimes, a removeNetwork call could remove more than one configured network at a time (e.g. a network and its OWE config), so that the subsequent call may find its target config missing and return false. Currently, this will cause an exception to be raised, even though the intended outcome is achieved. Therefore, it is more reliable to simply verify that the configured network list is cleared by the end of the removal process.

2022-01-13 04:12 UTC, xpconanfan requested changes

2022-01-13 04:12 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> +                Log.e("Encountered error while removing network: " + config);
let's still keep the failedConfigs list and log the list altogether if the clear failed at the end?

2022-01-13 04:14 UTC, xpconanfan requested changes

2022-01-13 04:14 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
>              if (!mWifiManager.removeNetwork(config.networkId)) {
we should probably add some context with inline comments on the new strategy.
this is because Wi-Fi stack has special types of networks (what's the official term?) that come and go on their own right?

2022-01-14 02:15 UTC, xianyuanjia reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/146)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @xianyuanjia and @xpconanfan)

___
*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 86 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/146#-MtAJOTGqVRUawIAZb1a-r1-86:-MtLMctEBSEtauP8RkFU:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/abb239def342d958aec3d2fad501aca599d83cc0/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L86)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

we should probably add some context with inline comments on the new strategy.
this is because Wi-Fi stack has special types of networks (what's the official term?) that come and go on their own right?
</blockquote></details>

Done.
___
*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 87 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/146#-MtAJOTGqVRUawIAZb1a-r1-87:-MtLMdknDR4-6XHWSkuZ:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/abb239def342d958aec3d2fad501aca599d83cc0/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L87)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's still keep the failedConfigs list and log the list altogether if the clear failed at the end?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-14 03:21 UTC, xpconanfan approved these changes

2022-01-14 19:43 UTC, xianyuanjia reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/146)* status: all files reviewed, 2 unresolved discussions (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2022-01-14 19:44 UTC, merged