Use intent to enable BT discoverability for T+; handle dialog with UIAutomator
google/mobly-bundled-snippets pull request #149
Opened 2022-05-04 22:56 UTC by xianyuanjia

2022-05-12 00:49 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/149)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xianyuanjia and @xpconanfan)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 223 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/149#-N1pjMOk1STza7ek-S-j:-N1pjMOk1STza7ek-S-k:b-2injib) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/2897fa78aba9d5be58873cd560bd26c341d3968f/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L223)):*
> ```Java
>         }
>         if (Build.VERSION.SDK_INT > 30) {
>             // setScanMode is removed from public SDK for T and above, so uses an intent instead.
> ```

if this is removed, does that mean we can trigger a scan without calling this at all?
or has the discoverable flow changed completely (to intent)


<!-- Sent from Reviewable.io -->

2022-05-12 17:50 UTC, xianyuanjia commented
According to https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#ACTION_REQUEST_DISCOVERABLE, the device is not discoverable by default. An intent is needed to allow scanning.

2022-05-13 19:11 UTC, xpconanfan commented
I'm not sure if `androidx.test.uiautomator` would cause build errors for internal users' snippets that use this lib.
So make sure we run global presubmit when syncing to internal.

2022-05-13 19:11 UTC, xpconanfan approved these changes

2022-05-13 19:11 UTC, merged

2022-05-13 19:15 UTC, xianyuanjia commented
The plan is to make string replacements during sync to set the supported package name.