Add intent-based flow to enable Bluetooth for T and above.
google/mobly-bundled-snippets pull request #151
Opened 2022-05-18 01:30 UTC by xianyuanjia

2022-05-18 03:33 UTC, xpconanfan requested changes

2022-05-18 03:33 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +            // BluetoothAdapter#enable is removed from public SDK for T and above, so uses an intent
this doesn't explain why there is a separate block for `> 30`

2022-05-18 03:33 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +        } else if (!mBluetoothAdapter.enable()) {
is this `else` correct?

2022-05-18 17:30 UTC, xianyuanjia reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/151)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @xpconanfan)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 123 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/151#-N2JmTNpWXKKdM7RXz_H-r1-123:-N2NCKyc378PctePxKDF:bf7mbi9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/069fc58e424be4fa6a668940491f0c68a6fa869c/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L123)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this doesn't explain why there is a separate block for `> 30`
</blockquote></details>

The `> 30` block is in another method, where I updated a comment. Splitting into another change.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 134 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/151#-N2JmTNpWXKKdM7RXz_H-r1-134:-N2NCmUJ-sa1O4SPKTRy:b678bo8) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/069fc58e424be4fa6a668940491f0c68a6fa869c/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L134)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

is this `else` correct?
</blockquote></details>

It calls the API directly only if the API level is not `> 32` 


<!-- Sent from Reviewable.io -->

2022-05-18 21:25 UTC, xpconanfan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/151#-:-N2O3-qqBDmXW90q3ed9:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2022-05-18 21:27 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/151)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @xianyuanjia and @xpconanfan)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 122 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/151#-N2O3KP-BgYJ-KQGUAq0:-N2O3KP-BgYJ-KQGUAq1:b-ippc1f) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/66da8196e9087bb24c5919e7ebcd9d4217ea8b6a/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L122)):*
> ```Java
>         waitForStableBtState();
> 
>         if (Build.VERSION.SDK_INT > 32) {
> ```

let's use `>=33` so it's clearer
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 123 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/151#-N2O3ElR-WrD_z1JNZat:-N2O3ElS70fcD6QOAqUa:b-8jo373) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/66da8196e9087bb24c5919e7ebcd9d4217ea8b6a/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L123)):*
> ```Java
> 
>         if (Build.VERSION.SDK_INT > 32) {
>             // BluetoothAdapter#enable is removed from public SDK for T and above, so uses an intent
> ```

let's use the number system instead of letters in comments


<!-- Sent from Reviewable.io -->

2022-05-19 07:28 UTC, xpconanfan approved these changes

2022-05-19 07:29 UTC, merged