Solve permission issues when performing btDiscoverAndGetResults
google/mobly-bundled-snippets pull request #169
Opened 2023-06-08 20:44 UTC by stplaydog

2023-06-13 17:50 UTC, xpconanfan requested changes

2023-06-13 17:50 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
> +        Log.d("Elevating permission require to enable support for wifi operation in Android Q+");
why does this say wifi when you are actually using it for bt?

is this copied from somewhere?

2023-06-13 17:50 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    public void btConfirmPair() throws Throwable {
shouldn't this be part of the Rpc that initiates the pairing instead?

2023-06-13 22:52 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
> +        Log.d("Elevating permission require to enable support for wifi operation in Android Q+");
Yes, it's copied from WifiManagerSnippet, let me consolidate this function.

2023-06-13 22:54 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    public void btConfirmPair() throws Throwable {
This is what missing from the device being paired, actually it needs a listener to autoconfirm the paring request. SL4A has a similar implementation: bluetoothStartPairingHelper

2023-06-13 23:03 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    public void btConfirmPair() throws Throwable {
Whichever Rpc initiates the pairing should include the confirmation right?

Or is this confirming an incoming pair request? If so, the name and documentation should be clear on that.

Right now this is pretty confusing.

2023-06-28 18:14 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +    public void btConfirmPair() throws Throwable {
Thanks, I've changed the name and documentation to clarify the purpose of this function.

2023-06-28 19:43 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/169)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @stplaydog)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 195 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/169#gh-1228496543:-NZ2Whyt4gBWIO8n6gcj:b6g5ler) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f8e153ede200336c20d519b6746ddfadc510c9e5/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L195)):*
<details><summary><i>Previously, stplaydog (Zhaoming Yin) wrote…</i></summary><blockquote>

Thanks, I've changed the name and documentation to clarify the purpose of this function.
</blockquote></details>

Something like `btStartAutoAcceptIncomingPairRequst` ?
And we should probably have a "Stop" for it as well?

Also, should the stop be part of the `shutdown`, or will the receiver automatically go away?


<!-- Sent from Reviewable.io -->

2023-07-10 22:56 UTC, stplaydog commented
> > _[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/169)_ status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @stplaydog)
> 
> _[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java` line 195 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/169#gh-1228496543:-NZ2Whyt4gBWIO8n6gcj:b6g5ler) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f8e153ede200336c20d519b6746ddfadc510c9e5/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L195)):_
> 
> Previously, stplaydog (Zhaoming Yin) wrote…
> Something like `btStartAutoAcceptIncomingPairRequst` ? And we should probably have a "Stop" for it as well?
> 
> Also, should the stop be part of the `shutdown`, or will the receiver automatically go away?

roger, implement the function similar to how it's handled in SL4A:

1. changed the name
2. add top function
3. add stop in the shutdown part

* test auto confirm (SUCCESS)

target `s.btEnable() -> s.btBecomeDiscoverable(1500) -> s.btSetName("target") -> s.btStartAutoAcceptIncomingPairRequest()`

source `s.btEnable() -> s.btDiscoverAndGetResults() -> s.btPairDevice('08:9E:08:35:01:C6')`

* test cancel auto confirm (NOT SUCCESS)

target `s.btEnable() -> s.btBecomeDiscoverable(1500) -> s.btSetName("target") -> s.btStartAutoAcceptIncomingPairRequest() -> s.btStopAutoAcceptIncomingPairRequest()`

source `s.btEnable() -> s.btDiscoverAndGetResults() -> s.btPairDevice('08:9E:08:35:01:C6')`

2023-07-19 03:06 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> -          UiAutomation uia = InstrumentationRegistry.getInstrumentation().getUiAutomation();
Please remove Unused imports: android.app.UiAutomation

2023-07-19 03:07 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> -                  throw new WifiManagerSnippetException("Failed to cleaup Ui Automation", e);
Please remove Unused class: WifiManagerSnippetException

2023-07-19 03:10 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +import java.util.HashMap;
In alphabetical order.

2023-07-19 03:11 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +        for (Map.Entry<String,BroadcastReceiver> entry : mReceivers.entrySet()) {
Need a space between comma and BroadcastReceiver

2023-07-19 17:45 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> -                  throw new WifiManagerSnippetException("Failed to cleaup Ui Automation", e);
WifiManagerSnippetException is still widely used in this class

2023-07-19 17:45 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +import java.util.HashMap;
done

2023-07-19 17:45 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
> +        for (Map.Entry<String,BroadcastReceiver> entry : mReceivers.entrySet()) {
done, thanks!

2023-07-19 17:45 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> -          UiAutomation uia = InstrumentationRegistry.getInstrumentation().getUiAutomation();
done

2023-07-19 20:04 UTC, stplaydog commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> -                  throw new WifiManagerSnippetException("Failed to cleaup Ui Automation", e);
removed unused WifiManagerSnippetException Ctor.

2023-07-19 20:05 UTC, ko1in1u approved these changes

2023-07-20 17:00 UTC, merged