Add RECEIVER_EXPORTED flag to portrait sys ui register receiver calls;
google/mobly-bundled-snippets pull request #176
Opened 2023-08-30 23:19 UTC by VitaliDim

Tested locally

2023-08-30 23:22 UTC, VitaliDim commented
@xpconanfan , @ko1in1u , @xianyuanjia  please review this PR.
Not able to add reviews via reviewers input

2023-08-30 23:24 UTC, xpconanfan commented
https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED

This is added in API level 33.

What happens when users try to use this on older Android versions?

2023-08-30 23:25 UTC, xpconanfan requested changes
Don't we need to handle compatibility with lower API levels?

2023-08-31 22:01 UTC, VitaliDim commented
Done, @xpconanfan please take a look.
Thank you

2023-09-05 16:51 UTC, xianyuanjia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/176#-:-NdaFE1y1savoH1_7qLM:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2023-09-05 17:26 UTC, VitaliDim commented
RPC verified, works as expected.
Tested on build: 10651996, target: seahawk-userdebug, SDK: 34

2023-09-06 16:49 UTC, xpconanfan commented
> fied, works as expected.
> Tested on build: 10651996, target: seahaw

Thanks for this.
But the main concern is this breaking for lower level APIs.
Did you test on lower level APIs and phones without changing the build config?

2023-09-06 19:48 UTC, VitaliDim commented
@xpconanfan I did not tested on lover APIs level.
For now we need move forward with BT Messenger automation.
This changes its a workaround for unblocking our efforts for SDK 34 and above.

2023-09-13 16:53 UTC, VitaliDim commented
@xpconanfan code for lower version SDK has not been changed at all. The changes related only for version 33 and above.

2023-10-02 23:55 UTC, VitaliDim commented
@xpconanfan verified on SDK 31, works as expected

2023-10-05 16:14 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java
> +            if (Build.VERSION.SDK_INT >= 33) {
looks like we need the same change at line 87

2023-10-15 20:45 UTC, xpconanfan approved these changes
Leaving the final Approval to [ko1in1u](https://github.com/ko1in1u)

2023-10-16 16:11 UTC, ko1in1u approved these changes

2023-10-16 16:16 UTC, VitaliDim reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/176)* status: all files reviewed, 1 unresolved discussion (waiting on @VitaliDim)



<!-- Sent from Reviewable.io -->

2023-10-16 18:43 UTC, merged