Introduces BluetoothHeadsetClientSnippet for interacting with the Bluetooth Headset Client profile(HFP).
google/mobly-bundled-snippets pull request #189
Opened 2024-03-07 10:38 UTC by nihald2000

The class provides functionality for:

Setting connection policies
Connecting and disconnecting from remote devices
Retrieving connection states
Managing voice recognition
Includes methods like:

btHeadsetClientSet
btHfp-connect
btHfp-disconnect
btHfp-getConnectionState
btHfp-startVoiceRecognition
btHfp-stopVoiceRecognition
Also utilizes BroadcastReceiver for handling Bluetooth events.

2024-03-07 10:39 UTC, nihald2000 reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nihald2000)



<!-- Sent from Reviewable.io -->

2024-03-07 17:52 UTC, nihald2000 reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsP1j-j-Q-St-C58m3E:-NsP1j-k53hnhEQEZHSW:bbhp22a) (no related file):*
@ko1inlu please review 

___


<!-- Sent from Reviewable.io -->

2024-03-07 18:04 UTC, xpconanfan requested changes
Did you try and confirm that this works?

2024-03-07 18:04 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java
> + * Copyright (C) 2017 Google Inc.
not 2017 any more

2024-03-07 18:04 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java
> +import android.bluetooth.BluetoothA2dp;
there are some unused imports?
could you run static analysis and linter before uploading

2024-03-07 18:09 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java
> +import android.bluetooth.BluetoothA2dp;
+1 please also try building and loading in mobly to make sure it works as you expect

2024-03-08 17:03 UTC, nihald2000 reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 3 unresolved discussions (waiting on @ko1in1u and @xpconanfan)



<!-- Sent from Reviewable.io -->

2024-03-08 22:04 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +import android.bluetooth.BluetoothAdapter;
Imported modules should be sorted alphabetically.

2024-03-08 22:04 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +import android.bluetooth.BluetoothAdapter;
Please remove unused modules.

2024-03-08 22:05 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +import android.util.Log;
Consider using `com.google.android.mobly.snippet.util.Log` so there is no need to define `TAG`.

2024-03-08 22:06 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +public class BluetoothHeadsetSnippet implements Snippet {
Missing a Javadoc comment.

2024-03-08 22:10 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +    private static class BluetoothHeadsetSnippetException extends Exception {
This nested class is unused, and can be removed.

2024-03-08 22:11 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        BluetoothHeadsetSnippetException(String msg) {
Constructor 'BluetoothHeadsetSnippetException' is never used.

2024-03-08 22:15 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +    private static boolean sIsHFPProfileReady = false;
This doesn't seem to need to be a static value

2024-03-08 22:17 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +    private final JsonSerializer mJsonSerializer = new JsonSerializer();
Please remove unused field like `mJsonSerializer` and `mBluetoothConnectedDevice `

2024-03-08 22:19 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        public void onServiceDisconnected(int var1) {
expect a  `@Override` here

2024-03-08 22:20 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
The `mContext` should be initialized in the constructor

2024-03-11 07:28 UTC, nihald2000 commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
The use of final for mContext ensures that once it's assigned a value in the constructor, it cannot be changed later. This helps enforce immutability and can make your code more robust.

2024-03-11 07:28 UTC, nihald2000 commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +import android.bluetooth.BluetoothAdapter;
done

2024-03-11 07:30 UTC, nihald2000 reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 14 unresolved discussions (waiting on @ko1in1u and @xpconanfan)



<!-- Sent from Reviewable.io -->

2024-03-11 07:35 UTC, nihald2000 reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 14 unresolved discussions (waiting on @ko1in1u and @xpconanfan)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java` line 2 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1516602787:-NsgQUbh5u-eou35Xjtl:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/6c1773b22b6bab4dfe892e781cdf9e4b8d7631bf/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java#L2)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not 2017 any more
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java` line 19 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1516604240:-NsgQWPS76mH3JIJFlgy:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/6c1773b22b6bab4dfe892e781cdf9e4b8d7631bf/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java#L19)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

+1 please also try building and loading in mobly to make sure it works as you expect
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 19 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518357881:-NsgQXurEUQLRsLdXd6E:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L19)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Please remove unused modules.
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 40 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518358513:-NsgQYlG7-h_SBSgxoGG:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L40)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Consider using `com.google.android.mobly.snippet.util.Log` so there is no need to define `TAG`.
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 42 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518358867:-NsgQ_8-8hqEyoE5ygW8:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L42)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Missing a Javadoc comment.
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 43 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518361507:-NsgQorBE2lgxAfHkrNG:b-1s4fzs) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L43)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

This nested class is unused, and can be removed.
</blockquote></details>

I've created a new commit where I've used above class
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 46 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518361800:-NsgQJZi3LFJBm1XHODe:bnnlhaw) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L46)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Constructor 'BluetoothHeadsetSnippetException' is never used.
</blockquote></details>

I've created a new commit where I've used the 'BluetoothHeadsetSnippetException'.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 57 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518365286:-NsgR06uBE440uZ7mX07:b98a74z) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L57)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Please remove unused field like `mJsonSerializer` and `mBluetoothConnectedDevice `
</blockquote></details>

Introducing a new method, `btHfpGetConnectedDevices`, where we utilize the `mJsonSerializer` for serialization
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 66 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518368373:-NsgQ8pC8WrN3gpOCIud:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L66)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

The non-constant portion of an equals check generally comes first. Prefer `action.equals(CONSTANT)` if action is non-null or `Objects.equals(action, CONSTANT)` if action is nullable
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 80 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518369321:-NsgQ6KXEi7atst-gtRA:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L80)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

expect a  `@Override` here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 16:18 UTC, nihald2000 reviewed
The project has been successfully rebuilt after these changes.

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NsiHdw-6jDlwyP1EMdU:b-vw0gbd)* status: 1 of 2 files reviewed, 15 unresolved discussions (waiting on @ko1in1u and @xpconanfan)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 52 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518364546:-NsiDRWxDKVzmHusRvq9:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L52)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

This doesn't seem to need to be a static value
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 57 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518365286:-NsiDQ869ISiM14zzY9g:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L57)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

The field `mBluetoothConnectedDevice` is never read, please remove it.
</blockquote></details>

Done.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 91 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1518372498:-NsiEqLaASm-rQSM0rEY:bjguitv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/142640c4118db0043809e4885989c63b4df4d534/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L91)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Then you can init like this way.

```
public class BluetoothHeadsetSnippet implements Snippet {
    private static final Context mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
```
</blockquote></details>

The use of 'mContext' as a static field inside a static context might lead to unexpected behavior. The 'InstrumentationRegistry.getInstrumentation().getTargetContext()' call may not be valid in a static initializer, and it could cause issues during testing or runtime
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 69 at r3](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1519864154:-NsiDOzP4KKJng_KSvhw:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/35f88c991178c7524a7fcab307a4f966dcc51fdb/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L69)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Consider using `com.google.android.mobly.snippet.util.Log`, it will use `mobly-log-tag` or package name as logging tag.

```
import com.google.android.mobly.snippet.util.Log;

Log.d("action: " + action);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 16:19 UTC, nihald2000 reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 15 unresolved discussions (waiting on @ko1in1u and @xpconanfan)



<!-- Sent from Reviewable.io -->

2024-03-11 16:50 UTC, nihald2000 commented
Hello Team,

We're approaching Android 13 development, and a reminder that
BluetoothAdapter#enable() and #disable() are deprecated.

Are there alternative APIs or approaches we should consider for managing
Bluetooth functionality?

On Mon, Mar 11, 2024, 8:31 PM Kolin Lu ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> <https://github.com/google/mobly-bundled-snippets/pull/189#discussion_r1519864154>
> :
>
> > +            super(msg);
> +        }
> +    }
> +
> +    private static boolean sIsHFPProfileReady = false;
> +    private Context mContext;
> +    private BluetoothHeadset mBluetoothHeadset;
> +    private static final int HEADSET = 1;
> +    private final JsonSerializer mJsonSerializer = new JsonSerializer();
> +    private static final BluetoothAdapter mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
> +    private BluetoothDevice mBluetoothConnectedDevice;
> +    private final BroadcastReceiver mReceiver = new BroadcastReceiver() {
> +        @Override
> +        public void onReceive(Context context, Intent intent) {
> +            String action = intent.getAction();
> +            android.util.Log.d("action",action);
>
> Consider using com.google.android.mobly.snippet.util.Log, it will use
> mobly-log-tag or package name as logging tag.
>
> import com.google.android.mobly.snippet.util.Log;
>
> Log.d("action: " + action);
>
> ------------------------------
>
> In
> src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> <https://github.com/google/mobly-bundled-snippets/pull/189#discussion_r1519869282>
> :
>
> > +public class BluetoothHeadsetSnippet implements Snippet {
> +    private static class BluetoothHeadsetSnippetException extends Exception {
> +        private static final long serialVersionUID = 1;
> +
> +        BluetoothHeadsetSnippetException(String msg) {
> +            super(msg);
> +        }
> +    }
> +
> +    private final String TAG = "BluetoothHeadsetSnippet";
> +    private static boolean sIsHFPProfileReady = false;
> +    private Context mContext;
> +    private BluetoothHeadset mBluetoothHeadset;
> +    private BluetoothProfile.ServiceListener mServiceListenner;
> +    private static final int HEADSET = 1;
> +    private final JsonSerializer mJsonSerializer = new JsonSerializer();
>
> The field mBluetoothConnectedDevice is never read, please remove it.
> ------------------------------
>
> In
> src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> <https://github.com/google/mobly-bundled-snippets/pull/189#discussion_r1519852746>
> :
>
> > +                sIsHFPProfileReady = true;
> +            }
> +        }
> +
> +        public void onServiceDisconnected(int var1) {
> +            Log.d(TAG, "onServiceDisconnected" + var1);
> +            if (var1 == HEADSET) {
> +                sIsHFPProfileReady = false;
> +                mBluetoothHeadset = null;
> +            }
> +        }
> +    };
> +
> +    public BluetoothHeadsetSnippet() {
> +        Log.d(TAG, "BluetoothHeadsetSnippet");
> +        mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
>
> Then you can init like this way.
>
> public class BluetoothHeadsetSnippet implements Snippet {
>     private static final Context mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/mobly-bundled-snippets/pull/189#pullrequestreview-1928049204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANBCNJTXJ3REGLNL5UXGJY3YXXIMDAVCNFSM6AAAAABEKXR6VSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRYGA2DSMRQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-13 06:12 UTC, nihald2000 commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
this will affect for BroadcastReceiver

2024-03-13 06:28 UTC, xpconanfan commented
Please open a separate request for those.

2024-03-13 08:15 UTC, nihald2000 commented
> Did you try and confirm that this works?
 
Yes, I have successfully built the project. its working

2024-03-13 21:59 UTC, ko1in1u reviewed
Confirmed that `btHfpGetConnectedDevices` and `btHfpgetConnectionState` RPCs are working.

```
>>> ad.mbs.btHfpGetConnectedDevices()
[
  {
    'DeviceType': 'DEVICE_TYPE_DUAL',
    'BondState': 'BOND_BONDED',
    'Name': 'bt_classic',
    'UUIDs': [...],
    'Address': ...,
  },
]
>>> ad.mbs.btHfpgetConnectionState('bt_classic')
2
```

Could you help to clarify if you have tested `btHfpstartVoiceRecognition` and `btHfpstopVoiceRecognition`? If so, how to test them?

2024-03-14 07:23 UTC, zsyai reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 19 unresolved discussions (waiting on @ko1in1u, @nihald2000, and @xpconanfan)

___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvpPN7EA-MMIrkluOf):*
I don't see these two methods in your code. Did you delete them?



_Code quote:_
```
  btHfp-connect
  btHfp-disconnect
```
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 110 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvoCNf1Rl9eoTme10r:-NsvoCNf1Rl9eoTme10s:br6n5ef) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L110)):*
> ```Java
>      * @throws BluetoothHeadsetSnippetException If no device with the specified name is connected via HEADSET.
>      */
>     @Rpc(description = " Returns connection state.")
> ```

Extraneous space before the first letter.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 111 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvoSgQEsXwVbkQGsWQ:-NsvoSgQEsXwVbkQGsWR:b902irp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L111)):*
> ```Java
>      */
>     @Rpc(description = " Returns connection state.")
>     public int btHfpgetConnectionState(String name) throws BluetoothHeadsetSnippetException {
> ```

Here and elsewhere. Why use the "name" to select paired device? What if there are multiple devices with the same name? Could we use the address of paired device?



_Code quote:_
```Java
String name
```
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 130 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-Nsvp6sz148ziuZXtxn1:-Nsvp6sz148ziuZXtxn2:b90b6fh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L130)):*
> ```Java
>      */
>     @Rpc(description = "Starts voice recognition.")
>     public boolean btHfpstartVoiceRecognition(String name) throws BluetoothHeadsetSnippetException{
> ```

Here and elsewhere. Please use "lowerCamelCase" for all method names in this class, eg. btHfpStartVoiceRecognition.



_Code quote:_
```Java
btHfpstartVoiceRecognition
```


<!-- Sent from Reviewable.io -->

2024-03-15 08:42 UTC, nihald2000 reviewed
Introducing the btHfpIsVoiceRecognitionSupported method to Checks whether the headset supports voice recognition;.
if btHfpIsVoiceRecognitionSupported method is true then start and stop voice recognition will work
ad.mbs.btHfpstartVoiceRecognition("Infinity GLIDE N200")
ad.mbs.btHfpstopVoiceRecognition("Infinity GLIDE N200")
output:
[TestBed] 03-14 13:14:59.540 INFO True
[TestBed] 03-14 13:14:59.586 INFO True
[TestBed] 03-14 13:15:01.671 INFO True
[TestBed] 03-14 13:15:03.732 INFO [{'DeviceType': 'DEVICE_TYPE_CLASSIC', 'BondState': 'BOND_BONDED', 'Name': 'Infinity GLIDE N200', 'UUIDs': ['00001101-0000-1000-8000-00805f9b34fb', '0000111e-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb'], 'Address': 'F4:4E:FC:A7:BE:53'}]

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NswCCQP60TfFnVL8yhZ:b-43fvr3)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)

___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvpPN7EA-MMIrkluOf):*
<details><summary><i>Previously, zsyai wrote…</i></summary><blockquote>

I don't see these two methods in your code. Did you delete them?
</blockquote></details>

yes 
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 59 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1523881460:-Nt0FMzIDIGddI4weWAB:b-831afd) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L59)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Methods and non-static variables should be named in lowerCamelCase, with acronyms treated as words. So this name should follow the same naming rule as the method `btHfpGetConnectedDevices` which is `sIsHfpProfileReady`
</blockquote></details>

In the latest commit, I followed the above changes.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 110 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvoCNf1Rl9eoTme10r:-Nt0FjoB2bJ3Mfm1b0qP:b-831afd) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L110)):*
<details><summary><i>Previously, zsyai wrote…</i></summary><blockquote>

Extraneous space before the first letter.
</blockquote></details>

In the latest commit, I followed the above changes.
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 111 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-NsvoSgQEsXwVbkQGsWQ:-Nt0FoiOBYJBnAfsGN9A:b-6jgud) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L111)):*
<details><summary><i>Previously, zsyai wrote…</i></summary><blockquote>

Here and elsewhere. Why use the "name" to select paired device? What if there are multiple devices with the same name? Could we use the address of paired device?
</blockquote></details>

In the latest commit, I followed the above changes. used string deviceAddress. 
___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 130 at r4](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-Nsvp6sz148ziuZXtxn1:-Nt0GCRJ99ydEI6UbK3o:b-831afd) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eb39934cf3eab38438a87b4cb85087cff0aa2549/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L130)):*
<details><summary><i>Previously, zsyai wrote…</i></summary><blockquote>

Here and elsewhere. Please use "lowerCamelCase" for all method names in this class, eg. btHfpStartVoiceRecognition.
</blockquote></details>

In the latest commit, I followed the above changes.


<!-- Sent from Reviewable.io -->

2024-03-15 17:19 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +import com.google.android.mobly.snippet.rpc.Rpc;
In alphabetical order.

2024-03-15 17:19 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        Utils.waitUntil(() -> sIsHFPProfileReady, 60);
The correct usage is using `EventCache` and `SnippetEvent` inside BroadcastReceiver, and `Utils.waitForSnippetEvent` outside BroadcastReceiver. Please follow the same style as [SmsSnippet](https://github.com/google/mobly-bundled-snippets/blob/master/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java)

2024-03-15 17:19 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +        mContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
Please use SnippetEvent in BroadcastReceiver so you won't hit this problem.

2024-03-15 19:26 UTC, ko1in1u commented
The [SmsSnippet](https://github.com/google/mobly-bundled-snippets/blob/master/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java) is an example.

Inside `BroadcastReceiver`, save data in [SnippetEvent](https://github.com/google/mobly-bundled-snippets/blob/c00e2d62621cf6526c67515b4e50baec79b8339d/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L231) then post to [EventCache](https://github.com/google/mobly-bundled-snippets/blob/c00e2d62621cf6526c67515b4e50baec79b8339d/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L245).
Outside `BroadcastReceiver`, use [Utils.waitForSnippetEvent](https://github.com/google/mobly-bundled-snippets/blob/c00e2d62621cf6526c67515b4e50baec79b8339d/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L132) to get the data you need.

So you don't have to declare a boolean `sIsHFPProfileReady`, then both `BroadcastReceiver` and general methods read from this value.

2024-03-18 07:22 UTC, nihald2000 reviewed
SnippetEvent event = new SnippetEvent(mCallbackId, SMS_RECEIVED_EVENT_NAME)
required: String,String
but `sIsHFPProfileReady`is boolean value.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NtFKgNq3DdYJLs1SDYm:bojs2ji)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)



<!-- Sent from Reviewable.io -->

2024-03-18 10:05 UTC, nihald2000 reviewed
Eliminated BroadcastReceiver and using PairingBroadcastReceiver

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NtG0XkPEvKOJKfUkNQ8:bb244d2)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)



<!-- Sent from Reviewable.io -->

2024-03-18 10:06 UTC, nihald2000 reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: all files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)



<!-- Sent from Reviewable.io -->

2024-03-18 18:54 UTC, nihald2000 reviewed
java.util.concurrent.TimeoutException: Timed out waiting(60000 millis) for SnippetEvent: BluetoothHeadsetCallback
getting above TimeoutException

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NtHuYOJ6UT8wx3bxcIN:b-tb6cnz)* status: all files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)



<!-- Sent from Reviewable.io -->

2024-03-18 21:21 UTC, ko1in1u commented
> java.util.concurrent.TimeoutException: Timed out waiting(60000 millis) for SnippetEvent: BluetoothHeadsetCallback getting above TimeoutException
> 
> > _[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NtHuYOJ6UT8wx3bxcIN:b-tb6cnz)_ status: all files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)

The TimeoutException is bc of not receive such event until timeout, it should debug from the logic when posting event. (e.g. never receive the expected event?)

2024-03-19 05:59 UTC, nihald2000 reviewed
Boolean flags have been utilized in both files, `BluetoothA2DPSnippet.java` and `BluetoothHearingAidSnippet.java`, with the variables `isHearingAidProfileReady` and `sIsA2dpProfileReady`, respectively

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#-:-NtKAGj0EfepAXQi0YgQ:b-p6h08t)* status: all files reviewed, 21 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)



<!-- Sent from Reviewable.io -->

2024-03-20 20:04 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
> +                mBluetoothHeadset = (BluetoothHeadset)profile;
looks like `mBluetoothHeadset` can already indicate which callback was invoked
why do we need a separate bool to signal the same state at all?
just use `mBluetoothHeadset` to make the judgement

2024-03-21 06:11 UTC, nihald2000 reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)* status: 1 of 2 files reviewed, 22 unresolved discussions (waiting on @ko1in1u, @xpconanfan, and @zsyai)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java` line 73 at r7](https://reviewable.io/reviews/google/mobly-bundled-snippets/189#gh-1532779177:-NtUcVAU0eUD47Kv84Rd:b-t4xgvw) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c93d27f22b94f1e501ebe7c1c1696d43bb897c48/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java#L73)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

looks like `mBluetoothHeadset` can already indicate which callback was invoked
why do we need a separate bool to signal the same state at all?
just use `mBluetoothHeadset` to make the judgement
</blockquote></details>

yes i have removed boolean flag in latest commit please review 


<!-- Sent from Reviewable.io -->

2024-03-21 17:28 UTC, merged