Add the internet check for wifi connection
google/mobly-bundled-snippets pull request #195
Opened 2024-06-20 16:47 UTC by kaishi05

Two benefits to add internet check
1) Ensure the DHCP and internet validation are completed and WLAN medium is truly ready. 2) Simplify the existing L2 connection check which sometimes fails to detect WiFi connection while the internet WiFi is already connected.

This check is backward compatible as it doesn't change the existing methods' behavior. Snippet users need to call wifiConnectSimpleWithInternetCheck() and wifiConnectWithInternetCheck() to check internet while existing methods don't check.

2024-06-29 05:44 UTC, xpconanfan requested changes
These RPCs are not specific to wifi network right?
Seem like they belong to the network snippet?

2024-07-01 17:22 UTC, kaishi05 commented
Removed the internet check and only check if the wifi is available using networkCallback for L+ devices.. Removed networkId check in Pre-L devices.

Note that it is recommended by the framework to use networkCallback to check Wifi status. So this file is the right place to add the networkCallback to check Wifi status.

2024-07-01 17:55 UTC, kaishi05 commented
Please  review 2nd comment.

2024-07-02 09:39 UTC, mhaoli approved these changes
LGTM as this is the recommended WiFi status check approach from WiFi framework.

And this approach works for both WiFi network w/ and w/o internet access.

2024-07-02 09:39 UTC, mhaoli commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> +              + configuration);
Could we revert the indent change in this PR? The modified lines look inconsistent with unmodified lines.

2024-07-02 18:17 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> +              + configuration);
revert the unnecessary indent changes.

2024-07-03 16:09 UTC, xpconanfan approved these changes

2024-07-03 16:19 UTC, merged