Update WifiManagerSnippet.java
google/mobly-bundled-snippets pull request #202
Opened 2024-08-05 20:57 UTC by kaishi05

Add isTdlsSupported() and isAwareAvailable()

2024-08-05 21:01 UTC, xpconanfan requested changes

2024-08-05 21:01 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> +    public boolean isAwareAvailable() throws Throwable {
this class is not the place to add wifi aware functionalities.

pls remove

2024-08-05 21:02 UTC, xpconanfan commented
please provide contextual PR title and descriptions
current ones are too generic

2024-08-21 05:27 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
> +    public boolean isAwareAvailable() throws Throwable {
Move Aware change to a new snippet file.

2024-08-21 05:31 UTC, xpconanfan approved these changes

2024-08-21 05:34 UTC, kaishi05 commented
Please help merge the change.

2024-08-21 05:38 UTC, merged