Add new snippet for adding a contact with the given email address
google/mobly-bundled-snippets pull request #203
Opened 2024-08-08 22:35 UTC by ko1in1u

Example usage:

```py
# Add a device-only contact.
ad.mbs.addContact('new.contact@gmail.com')

# Add a contact to a specific Google account.
ad.mbs.addContact('new.contact2@gmail.com', 'my.email@gmail.com)
```

2024-08-09 19:12 UTC, xpconanfan requested changes

2024-08-09 19:12 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContentProviderOperationSnippet.java
> +/* Snippet class for operating contacts. */
`ContentProviderOperation` can be used to set many things right?

If you just want to operate contact, name this `ContactSnippet`?

Like `contactAdd`, `contactRemove`?

2024-08-09 19:19 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/ContentProviderOperationSnippet.java
> +/* Snippet class for operating contacts. */
Done.

2024-08-13 18:26 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +        // Request a sync to the account.
what does requesting sync mean?

let's have javadoc for how to use this

2024-08-13 18:47 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +        // Request a sync to the account.
This is for syncing the new contact data to gmail account, move it to as separated function and add Javadoc.

2024-08-13 18:50 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +  private void requestSync(String accountEmailAddress) {
`requestSync` can mean many things so it's too generic a name.

2024-08-13 18:51 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +    if (accountEmailAddress != null) {
this step seems entirely separate from the rest of this method.
should probably just make this step a separate Rpc?

2024-08-13 19:02 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +    if (accountEmailAddress != null) {
Done.

2024-08-13 19:25 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +    String accountType = accountEmailAddress == null ? null : GOOGLE_ACCOUNT_TYPE;
the account type can be an email address?

2024-08-13 19:25 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +            .withValue(ContactsContract.RawContacts.ACCOUNT_NAME, accountEmailAddress).build());
we allow the value here to be null?

2024-08-13 21:33 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +    String accountType = accountEmailAddress == null ? null : GOOGLE_ACCOUNT_TYPE;
Account type must be "google.com" for Google account.

2024-08-13 21:34 UTC, ko1in1u commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +            .withValue(ContactsContract.RawContacts.ACCOUNT_NAME, accountEmailAddress).build());
Yes, if email address is null then the contact will be saved on device.

2024-08-14 00:09 UTC, xpconanfan requested changes

2024-08-14 00:09 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
> +    String accountType = accountEmailAddress == null ? null : GOOGLE_ACCOUNT_TYPE;
Looks like this is really `addGoogleContact`?
can we just add this one specific feature without implicit behaviors of optional param?

2024-08-14 00:20 UTC, xpconanfan approved these changes

2024-08-14 01:29 UTC, merged