Rename RPC methods with wifi prefix.
google/mobly-bundled-snippets pull request #209
Opened 2024-08-21 19:05 UTC by kaishi05

2024-08-21 19:11 UTC, xpconanfan requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/209)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kaishi05)

___
*[`src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java` line 47 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/209#-O4qL8se4LKPhyimR3mt:-O4qL8se4LKPhyimR3mu:b-e9hrso) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d3d513b919c07b321d9106a93e429c48dc6ded1b/src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java#L47)):*
> ```Java
>   public boolean wifiAwareIsAvailable() throws Throwable {
>     if (!mIsAwareSupported || mWifiAwareManager == null) {
>       return false;
> ```

we should throw an exception here instead.

Is available is clearly a different concept from `is supported`.

When it's not supported, `is available` is an invalid question, hence it should raise?


<!-- Sent from Reviewable.io -->

2024-08-21 20:26 UTC, kaishi05 commented
As suggested, throw an exception when it is not supported.

2024-08-21 20:36 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (!mIsAwareSupported || mWifiAwareManager == null) {
one of these two is sufficient for determining whether wifi aware is supported on this device right?
can we simplify the logic and only have one signal var instead?

2024-08-21 23:28 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (!mIsAwareSupported || mWifiAwareManager == null) {
Done.

2024-08-22 00:24 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
let's use `isAwareSupported` instead as it's more direct?

2024-08-22 00:30 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
There is a small chance that mWifiAwareManager could be still null even if isAwareSupported = true. So I prefer the null check.

2024-08-22 00:33 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
But that null doesn't necessarily mean wifi aware is not supported.
If you are worried about that edge case, we should handle that separately with a different exception

2024-08-22 00:35 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
Null means WifiAware service is not running and as the result Aware is not supported.

2024-08-22 01:26 UTC, xpconanfan commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
"supported" means this device can support aware.
"available" means this device can perform wifi aware actions right now.

the edge case you brought up means Aware is supported on this device, but wifi aware manager being null
but that doesn't mean the wifi aware manager can't be null on this device ever?

2024-08-22 01:39 UTC, kaishi05 commented on src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
> +        if (mWifiAwareManager == null) {
Okay. If you were more clear on original suggestion, we would have less back and forth on this.  I made the change. Let's move on.

2024-08-22 05:51 UTC, xpconanfan approved these changes

2024-08-22 05:51 UTC, merged