Prebuild and release APK file
google/mobly-bundled-snippets pull request #215
Opened 2024-12-17 07:12 UTC by ko1in1u

Enhancement:

- Prebuilt APK: To expedite the development process, prebuilt APK is now included in the GitHub release. This eliminates the need for users to build the APK after cloning the MBS project, saving valuable time and effort.

This change simplifies the initial setup and allows users to quickly deploy and test the application.

2024-12-17 18:38 UTC, xianyuanjia requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/215)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)

___
*[`release/mobly-bundled-snippets.apk` line 0 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/215#-OEKu8OJDwEYQ4ZN4NLa:-OEKu8OJDwEYQ4ZN4NLb:b-rwuoly) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/ede7c74c4cfd5ffafbd66d6dd4bc60ae3cf647a9/release/mobly-bundled-snippets.apk#L0)):*
It's recommended to add binaries to https://github.com/google/mobly-bundled-snippets/releases. Then we wouldn't need to push the APK to the repo directly.


<!-- Sent from Reviewable.io -->

2024-12-18 02:35 UTC, ko1in1u commented
Got it, I'll move the release to https://github.com/google/mobly-bundled-snippets/releases. Thanks for the suggestion.

2024-12-18 19:11 UTC, xianyuanjia commented
We should still have the CHANGELOG created.

2025-02-14 20:05 UTC, ko1in1u commented
> We should still have the CHANGELOG created.

Sorry for late reply. I've removed the apk in the PR.

2025-02-14 21:42 UTC, xianyuanjia requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/215)* status: all files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[`CHANGELOG.md` line 3 at r2](https://reviewable.io/reviews/google/mobly-bundled-snippets/215#-OJ5P1Ne6V7aMRQFYEOL:-OJ5P1NfDjvAub0xIH5c:b-r966jr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8886578fba83cb12817d199ef83c06bd20ebf8e1/CHANGELOG.md#L3)):*
> ```Markdown
> # Mobly Bundled Snippets (MBS) APK Release History
> 
> ## 0.0.1: Initial release
> ```

For the first release we should consider this as version 1.0. 



_Code quote:_
```Markdown
 0.0.1
```


<!-- Sent from Reviewable.io -->

2025-02-14 21:46 UTC, ko1in1u commented
> 
> For the first release we should consider this as version 1.0.
> 
> _Code quote:_
> 
> ```
>  0.0.1
> ```

The release has tagged as 0.0.1 in https://github.com/google/mobly-bundled-snippets/releases/tag/0.0.1. Should we upload a new 1.0 to replace it?

2025-02-14 22:24 UTC, xianyuanjia approved these changes
If the release package is already tagged, then we can just leave the version as is.

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/215#-:-OJ5Yu33AVvJbTpt6xiW:booo77x)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)



<!-- Sent from Reviewable.io -->

2025-02-14 22:25 UTC, xianyuanjia reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/215#-:-OJ5ZI804l_HMvDK0LzA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)



<!-- Sent from Reviewable.io -->

2025-02-14 22:50 UTC, ko1in1u commented
> If the release package is already tagged, then we can just leave the version as is.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/215#-:-OJ5Yu33AVvJbTpt6xiW:booo77x)_ status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)

Got it, thank you.

2025-02-14 22:50 UTC, merged